### ISSUE TITLE
Why do you we need THX functions?

### ISSUE THREAD

**Issue by dnmfarrell** [dnmfarrell/URI-Encode-XS#11]
Reading the [perlguts](http://perldoc.perl.org/perlguts.html) entry on THX, it suggests they're only needed for var args functions:

"When a core function calls another, it must pass the context. This is normally hidden via macros. Consider sv_setiv . It expands into something like this:

```
    #ifdef PERL_IMPLICIT_CONTEXT
      #define sv_setiv(a,b)      Perl_sv_setiv(aTHX_ a, b)
      /* can't do this for vararg functions, see below */
    #else
      #define sv_setiv           Perl_sv_setiv
    #endif
```

This works well, and means that XS authors can gleefully write:

```
    sv_setiv(foo, bar);
```

and still have it work under all the modes Perl could have been compiled with.

This doesn't work so cleanly for varargs functions, though, as macros imply that the number of arguments is known in advance. Instead we either need to spell them out fully, passing aTHX_ as the first argument (the Perl core tends to do this with functions like Perl_warner), or use a context-free version."

None of our functions have variable numbers of arguments - so why do we need THX functions?

**Comment by arodland** [comment]
You've misunderstood. The context argument is _always_ needed (if `PERL_IMPLICIT_CONTEXT` is enabled), varargs or not; the macros just hide it from the caller. The comment about varargs is saying that the macro trick doesn't work for varargs functions (at least not portably), so in that case the detail of `aTHX_` can't be hidden from the caller and needs to be included at every callsite.

Since you're using `PERL_NO_GET_CONTEXT`, `aTHX_` doesn't expand into a function call to get the context; it just propagates it from its lexical environment. Your XSUBs get the context automatically, but if an XSUB calls a function, and that function calls the perl API, then the context needs to be passed into the function — which is exactly the case for `uri_encode_dsv` and `uri_decode_dsv`. Because those aren't varargs functions, they can have the `aTHX_` hidden behind a macro, as indeed they already have.

**Comment by dnmfarrell** [comment]
@arodland got it, thank you!
